### ISSUE TITLE
Omnibug tab disabled/nonfunctional in Firefox 36.0

### ISSUE THREAD

**Issue by robpointmarc** [simpsora/omnibug#13]
Omnibug stops working within Firebug in latest version of Firefox.  
Omnibug tab is disabled and the panel does not show any site marketing pixel requests.

**Comment by simpsora** [comment]
Hi @robpointmarc, thanks for the bug report!  I'll have a look at it this evening.

**Comment by tryandls** [comment]
Confirming the same issue - 2 different PCs running FF36 and FB 2.0.8

**Comment by beegeok** [comment]
Faced the same issue in Firefox 36.0

**Comment by simpsora** [comment]
This issue is fixed in https://github.com/simpsora/omnibug/releases/tag/omnibug-0.5.509.  Thanks everyone for the bug reports!
