### ISSUE TITLE
Omnibug has stopped working w/ FF 36.0.1 and Firebug 2.0.8

### ISSUE THREAD

**Issue by aramos-cit** [simpsora/omnibug#17]

**Comment by MisterPhilip** [comment]
What version of Omnibug are you running? There was [a release](https://github.com/simpsora/omnibug/releases/tag/omnibug-0.5.509) last week to fix it.

**Comment by aramos-cit** [comment]
Hi @MisterPhilip , thanks for pointing me out to the newest release. Just realized I had .502 that I got from https://addons.mozilla.org/en-US/firefox/addon/omnibug/

Thanks

**Comment by simpsora** [comment]
Hi @aramos-cit, thanks for the issue report.  I am waiting for the fixed version of Omnibug to get approved by Mozilla.  Hopefully will be done soon!

**Comment by simpsora** [comment]
(and thanks @MisterPhilip for your comments as well!)
