### ISSUE TITLE
Add support for POST requests

### ISSUE THREAD

**Issue by simpsora** [simpsora/omnibug#18]
Email from a user:

> Any chance you could update the Omnibug Plugins to detect POST requests please?
> 
> Adobe Analytics (Omniture) have recently introduced HTTP POST support for data collection however the Omnibug plugins for both Chrome and Firefox don't currently pick these requests up.
> 
> The Adobe release notes found at https://marketing.adobe.com/resources/help/en_US/whatsnew/ contain the following information regarding the HTTP Post requests:
> 
> AppMeasurement for JavaScript and Flash now send image requests using POST in some circumstances to avoid request truncation that occurs at 2000 bytes in some browsers. After this update, Internet Explorer 8+ will no longer truncate request data at 2000 bytes, reducing errors and data loss for some variables. For example, if the browser is Internet Explorer 9 and the image URL is 1900 bytes, then the request is sent using HTTP GET. If it is 2100 bytes, the request is sent using HTTP POST. 
> Note that the Adobe Debugger does not inspect hits sent using HTTP POST. If the Adobe Debugger doesn’t show data in Internet Explorer, use a packet analyzer or the built-in network tools to examine the network traffic directly, or inspect the hit in a browser that does not truncate URLs, such as Chrome or Firefox. 
> This functionality requires AppMeasurement for JavaScript 1.4.1+ and the visitor ID service 1.3.2+.
> 
> I believe Google Analytics also now sends POST requests under certain user interactions as well.

**Comment by simpsora** [comment]
Screenshot from Omnibug when doing a POST request:
![3d9d3c24-728f-41b7-a129-32b004e28934](https://cloud.githubusercontent.com/assets/735585/6995042/7aac51a8-db72-11e4-81af-30506b218087.png)

Screenshot from HTTPFox for a similar request:
![c7adc393-8f22-4769-af1d-23b0ab7f0b37](https://cloud.githubusercontent.com/assets/735585/6995043/94a657d4-db72-11e4-970a-c4b2f4636f2d.png)

**Comment by simpsora** [comment]
I've looked into this, and it's not a small piece of work -- Firefox doesn't make it easy to access a request's POST data!

This will require using Firefox's observer service (specifically `http-on-modify-request`) to get the POST data -- it's not available from the `nsIWebProgressListener` interface, unfortunately.  I've done some work in that direction, but at the moment Omnibug still uses the progress listener interface.

**Comment by muellerr1** [comment]
#32 Not sure if this PR will work, but I've had success with the Chrome extension. I don't know much about the Firefox dev process but I'd imagine there are similar hooks somewhere. I may go looking, but for now this is working for me on Chrome.

**Comment by CompleteAutomation** [comment]
Any updates on this enhancement request for firefox?

**Comment by simpsora** [comment]
https://github.com/simpsora/omnibug/pull/32 has been superseded by https://github.com/simpsora/omnibug/pull/37, which has been merged and will be released shortly.

/cc @CompleteAutomation
