### ISSUE TITLE
Won't show events fired

### ISSUE THREAD

**Issue by Queststjacobs** [simpsora/omnibug#21]
I'm having issues w/ the UI - when I choose the Omnibug tab within Firebug, and take an action on the page to fire an event, Firebug defaults to the HTML tab.
Even switching back to Omnibug, it doesn't display a list of events fired. It shows HTML.
How can I get this to show me actions taken within an environment with omniture tagging.

**Comment by MisterPhilip** [comment]
Hi @Queststjacobs  - What version of Firefox & Omnibug are you running?

**Comment by Queststjacobs** [comment]
The latest. 37

*Quest St. Jacobs*

**Comment by MisterPhilip** [comment]
What version for Omnibug? If it is older than 0.5.509, you'll need to update it as there was a fix for a similar sounding issue. I believe Mozilla still hasn't approved the updated version in the store, but you can still download the latest at http://omnibug.rosssimpson.com/

**Comment by simpsora** [comment]
Hi @Queststjacobs, as @MisterPhilip says, please try downloading a new version from the [Omnibug site](http://omnibug.rosssimpson.com/) -- there was a bug in a previous release, and the auto-update feature is not working for that release.  Please let us know if you continue to have problems!
