### ISSUE TITLE
Can't Clear Enabled Providers

### ISSUE THREAD

**Issue by jansara66** [simpsora/omnibug#27]
I would like to debug only 1 Provider by have previously selected 3 others. In the Omnibug Options panel none are selected so am unable to clear the list and start with only 1. Is this a bug? or is there another way to achieve this?

**Comment by MisterPhilip** [comment]
What version browser / Omnibug are you running?

**Comment by jansara66** [comment]
Good question, sorry about that. Firefox 35.0.1

**Comment by MisterPhilip** [comment]
Hi @jansara66 - Can you clarify the issue? I was able to load unselect all of the providers and then select only 1 to debug that single provider. 
![omnibug fw](https://cloud.githubusercontent.com/assets/950141/7951149/b692a5aa-0958-11e5-8e0c-572722e4162d.png)

**Comment by jansara66** [comment]
When I open my Omnibug preferences, none of the providers are checked, though 3 had been reporting in Omnibug. So I checking just the one I wanted, click OK and return to Omnibug. This does not reset the selection to the one I selected. All 3 providers continue to report. I reopen preferences and note that none of the providers are checked. It looks like the options are not persisting.

**Comment by MisterPhilip** [comment]
Which 3 are reporting for you? If you could load up `about:config` in your address bar and search for omnibug, do you see those providers set as true or false? 

I've had this happen before when there was a config mismatch, but the latest shouldn't have that issue.

**Comment by jansara66** [comment]
There are 21 providers in the config list and all are set to "true". Perhaps the site I was debugging only had 3 of these installed as only 3 were reporting and all look to be enabled? Is it OK to toggle these in the config list?

**Comment by MisterPhilip** [comment]
Yeah, it's safe to set them as false there. Let me know if that does the trick for you. Otherwise would you be willing to send me the website you're looking at (you can email me if you'd prefer it not to be public).

**Comment by jansara66** [comment]
Hi Philip, thanks so much for taking the time to help me with this. I have toggled off all the properties I do not want to track and all is working as expected now. I've used Omnibug on many sites and am really pleased to have it. Thanks again.

**Comment by MisterPhilip** [comment]
Good to hear! Let me know if anything else comes up
