### ISSUE TITLE
No Longer Works in Chrome

### ISSUE THREAD

**Issue by loffelmacher** [simpsora/omnibug#31]
I was using Omnibug in Chrome six months ago, and everything was great! Now I open it up today to check some tags and no love. Or maybe I'm doing it wrong? I tried a couple of different things to get it to work, one thing I tried was to enable it for Incognito, but no luck.

**Comment by MisterPhilip** [comment]
Hi @loffelmacher, a few questions for you to help debug a bit: 

  1. What version of Chrome are you running?
  1. Does the Omnibug tab show up in the developer tools?
  1. Do you have all of the providers you care about selected in the Extensions options?

**Comment by loffelmacher** [comment]
Apologies for the piss-poor bug report, here's some details for ya.

1.  47.0.2526.111 is my current version of Chrome.
2. The tab *does* show up, so that's good!
3. All providers are checked.

Thanks for this plugin btw! After filing this I opened Firefox installed there, everything is cool with the FF version.

**Comment by MisterPhilip** [comment]
No worries, thanks for the info! Dumb question, but do any other pages have tags on them? E.g. if you check this page you should see 1x call to Universal Analytics.

**Comment by loffelmacher** [comment]
In other words, open up the Omnibug on this page? I did so just now and no dice. Nothing appears in the Omnibug tab.

**Comment by MisterPhilip** [comment]
Hmm, okay. Let me play around with it, I have it working OK on Chrome 48. Could you send me a screenshot of your options page?

**Comment by loffelmacher** [comment]
Here you go. I just updated to Chrome 48 btw, still having issues. I'm going to try removing & reinstalling the plugin. 

Screenshot: https://www.evernote.com/l/AQiwmi0lV3JNsZo9Q9UjFMjqXZ0HTDSfGZQ

**Comment by MisterPhilip** [comment]
Great, thanks! Let me know if that solves it, otherwise I'll play around with it this evening.

**Comment by loffelmacher** [comment]
No luck with re-installing @MisterPhilip. I have quite a few extensions, idk if that's related, but it looks like the Chrome Dev Tools folks have been making a lot of changes, it might just be something related to those recent changes.

**Comment by MisterPhilip** [comment]
Not sure if you ever got this solved, but feel free to reopen/new ticket if you haven't!
