### ISSUE TITLE
No events are loading

### ISSUE THREAD

**Issue by jogindernitk** [simpsora/omnibug#34]
I was trying omnibug but its behavior is very unpredictable. It is not loading the events at all.
It works sometime on the same page and then it will not work at all. No events are getting loaded. 
I am using chrome.

**Comment by MisterPhilip** [comment]
What tool(s) are you looking to check against? Do you have an example URL that you're testing against? Under the extension options (Settings > Extensions > Omnibug > options), are the providers all checked?

**Comment by simpsora** [comment]
@jogindernitk: are you still experiencing this problem?  If so, please provide some detail and we'll look into it.
