### ISSUE TITLE
Omnibug Not working in Chrome

### ISSUE THREAD

**Issue by summerof69** [simpsora/omnibug#35]
Omnibug is not working with chrome. Earlier it used to work absolutely perfect however now it is creating problem and not working.

- I  resetted the chrome to factory setting and added omnibug again yet it worked for some time then it stopped.

- Omnibug is working in private window in chrome

- Omnibug  was working smoothly before (3-4 months) without any hiccups

- Site has proper tags and omnibug works in firefox propely

- Omnibug show in developer tab too

- I am using omnibug for Adobe Analytics

- Even Adobe Analytics debugger dont work too for the site
Chrome Version: 54.0.2840.99 m

Require your help at the earliest

**Comment by simpsora** [comment]
Thanks for the report @summerof69.

As I mentioned in my other post, I'm not spending much time on this project at the moment, but I'll look into it tomorrow.

One thing you could try would be to use a brand new Chrome profile, with no other extensions loaded.  It shouldn't matter, but sometimes we see extensions interfering with one another.

Cheers,
Ross

**Comment by summerof69** [comment]
Hi Sir

Thanks for responding. I found that the issue is not with Omnibug but with
corporate network which is preventing it to load properly. Sometimes
Omnibug works properly in corporate network and sometimes not. I validated
by checking the Omnibug in my home and mobile network where it worked
smoothly. I hope you could guide me what could cause this problem.

Regards
Harendra Sahu

**Comment by simpsora** [comment]
Hello @summerof69,

I'm afraid I can't give you too much help without knowing more about how it's failing, and under what circumstances.  Some things I'd look at:

- Is your corporate network blocking the requests?
- Could it be a CORS or XSS issue?
- Does it happen on multiple devices and/or browsers?

I'd watch the requests in a network monitor and see what's happening, and ensure the analytics are all working properly.  Omnibug doesn't do anything on the network, so once you fix the network issue, Omnibug should be working properly.
