### ISSUE TITLE
How to see the Post request of Adobe Analytics tag with Omnibug

### ISSUE THREAD

**Issue by summerof69** [simpsora/omnibug#36]
Post request tags are not visible in Omnibug. Is there any upcoming solution that we can expect from Omnibug. Or if there is any solution that I am missing here

**Comment by simpsora** [comment]
Hi @summerof69,

I'm sorry to say that Omnibug doesn't currently support analytics in POST requests.  It's something that's on my list to do, but I'm not spending much time on this project lately, I'm afraid.

Keep an eye on this issue -- if I do fix it, I'll comment here.

Cheers,
Ross

**Comment by simpsora** [comment]
Hi @summerof69,

This has been addressed in https://github.com/simpsora/omnibug/pull/37, and a new release will be pushed to the Chrome Web Store later today.
